package com.example.Student_Library_Management_System.service;


import com.example.Student_Library_Management_System.DTOs.StudentUpdateMobileReqDto;
import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.model.Card;
import com.example.Student_Library_Management_System.model.Student;
import com.example.Student_Library_Management_System.repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class StudentService {

    @Autowired
    StudentRepository studentRepository;


    public String createStudent(Student student){
        // student from postman is already the basic attributes set

        // card should be autogenerated when createStudent function is called

        Card card=new Card();
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudent(student);

        //student
        student.setCard(card);

        studentRepository.save(student);

        //by cascading effect child will automatically save.

        return "student and card added successfully...";

    }

    public String findNameByEmail(String email){

        Student student= studentRepository.findByEmail(email);
        return student.getName();
    }

    public List<Student> findByCountry(String country){

        List<Student> students=new ArrayList<>();

        Student student= (Student) studentRepository.findByCountry(country);

       students.add(student);
       return students;


    }

    public String updateMobile(StudentUpdateMobileReqDto studentUpdateMobileReqDto){

        //convert DTO to entity
        Student student=studentRepository.findById(studentUpdateMobileReqDto.getId()).get();

        student.setMobNo(studentUpdateMobileReqDto.getMobNo());

        studentRepository.save(student);

        return "update student successfully....";
    }
}
